"""Initial migration

Revision ID: 81fd7ae18a6a
Revises: 
Create Date: 2025-03-07 03:26:15.829385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fd7ae18a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('circuit_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('lap_record', sa.String(length=100), nullable=True),
    sa.Column('lap_record_year', sa.Integer(), nullable=True),
    sa.Column('map_img_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('team_principal', sa.String(length=100), nullable=True),
    sa.Column('base_location', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('current_points', sa.Float(), nullable=True),
    sa.Column('championships', sa.Integer(), nullable=True),
    sa.Column('race_wins', sa.Integer(), nullable=True),
    sa.Column('podiums', sa.Integer(), nullable=True),
    sa.Column('first_entry_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constructor_id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_img_url', sa.String(length=255), nullable=True),
    sa.Column('helmet_img_url', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('current_points', sa.Float(), nullable=True),
    sa.Column('championships', sa.Integer(), nullable=True),
    sa.Column('race_wins', sa.Integer(), nullable=True),
    sa.Column('podiums', sa.Integer(), nullable=True),
    sa.Column('pole_positions', sa.Integer(), nullable=True),
    sa.Column('fastest_laps', sa.Integer(), nullable=True),
    sa.Column('first_race_year', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.DateTime(), nullable=True),
    sa.Column('qualifying_date', sa.DateTime(), nullable=True),
    sa.Column('sprint_date', sa.DateTime(), nullable=True),
    sa.Column('fp1_date', sa.DateTime(), nullable=True),
    sa.Column('fp2_date', sa.DateTime(), nullable=True),
    sa.Column('fp3_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('favorite_driver_id', sa.Integer(), nullable=True),
    sa.Column('favorite_team_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['favorite_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('races')
    op.drop_table('drivers')
    op.drop_table('teams')
    op.drop_table('circuits')
    # ### end Alembic commands ###
